-- Table structure for table `classification`
--CREATE TABLE public.classification (
-- classification_id INT GENERATED BY DEFAULT AS IDENTITY,
-- classification_name CHARACTER VARYING NOT NULL,
-- CONSTRAINT classification_pk PRIMARY KEY (classification_id)
--);


-- Table structure for table `classification`
CREATE TABLE IF NOT EXISTS public.classification (
    classification_id INT GENERATED BY DEFAULT AS IDENTITY,
    classification_name CHARACTER VARYING(100) NOT NULL UNIQUE,
    CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);
