-- Table structure for `classification`
CREATE TABLE IF NOT EXISTS public.classification (
    classification_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Unique identifier for each classification
    classification_name VARCHAR(100) NOT NULL UNIQUE, -- Name of the classification, must be unique
    CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

-- Optional: Insert sample data for testing
INSERT INTO public.classification (classification_name)
VALUES 
    ('Cars'),
    ('Trucks'),
    ('SUVs')
ON CONFLICT DO NOTHING; -- Avoid duplicate entries if data already exists
