-- Create ENUM for account status
CREATE TYPE public.account_type AS ENUM ('Client', 'Employee', 'Admin');

ALTER TYPE public.account_type
    OWNER TO msilp;

-- CLASSIFICATION TABLE --
-- Table structure for table 'classification'
CREATE TABLE public.classification (
    classification_id INT GENERATED BY DEFAULT AS IDENTITY,
    classification_name CHARACTER VARYING NOT NULL,
    CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

-- INVENTORY TABLE --
-- Table structure for table 'inventory'
CREATE TABLE IF NOT EXISTS public.inventory (
    inv_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Auto-incrementing unique identifier
    inv_make CHARACTER VARYING NOT NULL, -- Manufacturer of the vehicle
    inv_model CHARACTER VARYING NOT NULL, -- Model of the vehicle
    inv_year CHAR(4) NOT NULL, -- Year of manufacture (fixed-length)
    inv_description TEXT NOT NULL, -- Description of the vehicle
    inv_image CHARACTER VARYING NOT NULL, -- Path to the vehicle image
    inv_thumbnail CHARACTER VARYING NOT NULL, -- Path to the vehicle thumbnail
    inv_price NUMERIC(9, 0) NOT NULL, -- Price with precision and scale
    inv_miles INT NOT NULL, -- Vehicle mileage
    inv_color CHARACTER VARYING NOT NULL, -- Vehicle color
    classification_id INT NOT NULL, -- Foreign key to classification
    CONSTRAINT fk_classification FOREIGN KEY (classification_id)
        REFERENCES public.classification (classification_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- ACCOUNT TABLE --
CREATE TABLE IF NOT EXISTS public.account (
    account_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Auto-incrementing unique identifier
    account_firstname CHARACTER VARYING NOT NULL, -- First name of the account holder
    account_lastname CHARACTER VARYING NOT NULL, -- Last name of the account holder
    account_email CHARACTER VARYING NOT NULL UNIQUE, -- Unique email address
    account_password CHARACTER VARYING NOT NULL, -- Store hashed passwords securely
    account_type account_type NOT NULL DEFAULT 'Client' -- Role of the account
);

-- WISHLISTS TABLE --
CREATE TABLE IF NOT EXISTS public.wishlists (
    wishlist_id SERIAL PRIMARY KEY, -- Auto-incrementing unique identifier
    inv_id INT NOT NULL, -- Foreign key referencing inventory table
    user_id INT NOT NULL, -- Foreign key referencing account table
    created_at TIMESTAMP DEFAULT NOW(), -- Timestamp of when the wishlist item was added
    CONSTRAINT fk_inventory FOREIGN KEY (inv_id) REFERENCES public.inventory (inv_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_account FOREIGN KEY (user_id) REFERENCES public.account (account_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- Populate classification table
INSERT INTO public.classification (classification_name)
VALUES ('Custom'), ('Sport'), ('SUV'), ('Truck'), ('Sedan')
ON CONFLICT DO NOTHING;

-- Populate inventory table
INSERT INTO public.inventory (
    inv_make, inv_model, inv_year, inv_description, inv_image, inv_thumbnail,
    inv_price, inv_miles, inv_color, classification_id
)
VALUES 
-- Add vehicles for SUVs
('Ford', 'Explorer', '2023', 'A powerful SUV for family adventures.', '/images/vehicles/explorer.jpg', '/images/vehicles/explorer-tn.jpg', 40000, 1000, 'Black', 3),
('Jeep', 'Grand Cherokee', '2022', 'A luxurious SUV with off-road capability.', '/images/vehicles/cherokee.jpg', '/images/vehicles/cherokee-tn.jpg', 45000, 8000, 'Red', 3),

-- Add vehicles for Sedans
('Toyota', 'Camry', '2022', 'A comfortable and reliable sedan.', '/images/vehicles/camry.jpg', '/images/vehicles/camry-tn.jpg', 24000, 5000, 'Blue', 5),
('Honda', 'Accord', '2021', 'An efficient sedan with advanced technology.', '/images/vehicles/accord.jpg', '/images/vehicles/accord-tn.jpg', 26000, 12000, 'White', 5),

-- Add existing inventory data
('Chevy', 'Camaro', '2018', 'If you want to look cool this is the car you need! This car has great performance at an affordable price. Own it today!', '/images/camaro.jpg', '/images/camaro-tn.jpg', 25000, 101222, 'Silver', 2),
('GM', 'Hummer', '2016', 'Do you have 6 kids and like to go offroading?', '/images/hummer.jpg', '/images/hummer-tn.jpg', 58800, 56564, 'Yellow', 4),
('Batmobile', 'Custom', '2007', 'Ever want to be a superhero? Now you can with the Batmobile.', '/images/batmobile.jpg', '/images/batmobile-tn.jpg', 65000, 29887, 'Black', 1),
('Mystery', 'Machine', '1999', 'Scooby and the gang always found luck solving their mysteries.', '/images/mystery-van.jpg', '/images/mystery-van-tn.jpg', 10000, 128564, 'Green', 1)
ON CONFLICT DO NOTHING;

-- Populate account table
INSERT INTO public.account (
    account_firstname, account_lastname, account_email, account_password, account_type
)
VALUES 
('Bruce', 'Wayne', 'bruce@wayneent.com', 'IamBatm@n', 'Client')
ON CONFLICT DO NOTHING;

-- Modify GM Hummer description
UPDATE public.inventory
SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
WHERE inv_make = 'GM' AND inv_model = 'Hummer';

-- Update inventory image paths
UPDATE public.inventory
SET inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
    inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');
