-- Create custom type for account status
CREATE TYPE public.account_type AS ENUM ('active', 'inactive', 'suspended');

-- Create classification table
CREATE TABLE public.classification (
    classification_id INT GENERATED BY DEFAULT AS IDENTITY,
    classification_name CHARACTER VARYING NOT NULL,
    CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

-- Populate classification table
INSERT INTO public.classification (classification_name)
VALUES ('Custom'), ('Sport'), ('SUV'), ('Truck'), ('Sedan');

-- Create inventory table
CREATE TABLE public.inventory (
    inv_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    inv_make CHARACTER VARYING NOT NULL,
    inv_model CHARACTER VARYING NOT NULL,
    inv_year CHARACTER(4) NOT NULL,
    inv_description TEXT NOT NULL,
    inv_image CHARACTER VARYING NOT NULL,
    inv_thumbnail CHARACTER VARYING NOT NULL,
    inv_price NUMERIC(9, 0) NOT NULL,
    inv_miles INTEGER NOT NULL,
    inv_color CHARACTER VARYING NOT NULL,
    classification_id INTEGER NOT NULL,
    CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)
);

-- Create relationship between classification and inventory tables
ALTER TABLE public.inventory
ADD CONSTRAINT fk_classification FOREIGN KEY (classification_id)
REFERENCES public.classification (classification_id) MATCH SIMPLE
ON UPDATE CASCADE
ON DELETE NO ACTION;

-- Populate inventory table
INSERT INTO public.inventory (
    inv_make, inv_model, inv_year, inv_description, inv_image, inv_thumbnail,
    inv_price, inv_miles, inv_color, classification_id
)
VALUES 
('Chevy', 'Camaro', '2018', 'If you want to look cool...', '/images/camaro.jpg', '/images/camaro-tn.jpg', 25000, 101222, 'Silver', 2),
('GM', 'Hummer', '2016', 'Do you have 6 kids and like to go offroading?', '/images/hummer.jpg', '/images/hummer-tn.jpg', 58800, 56564, 'Yellow', 4);

-- Create account table
CREATE TABLE public.account (
    account_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_firstname CHARACTER VARYING NOT NULL,
    account_lastname CHARACTER VARYING NOT NULL,
    account_email CHARACTER VARYING NOT NULL,
    account_password CHARACTER VARYING NOT NULL,
    account_type public.account_type NOT NULL DEFAULT 'active',
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);

-- Populate account table
INSERT INTO public.account (
    account_firstname, account_lastname, account_email, account_password, account_type
)
VALUES
('Bruce', 'Wayne', 'bruce@wayneent.com', 'IamBatm@n', 'active');

-- Add queries 4 and 6 from Task One
-- 4. Update GM Hummer description to "a huge interior"
UPDATE inventory
SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
WHERE inv_make = 'GM' AND inv_model = 'Hummer';

-- 6. Update image paths in the inventory table
UPDATE inventory
SET inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
    inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');
