-- Table structure for table `inventory`
CREATE TABLE IF NOT EXISTS public.inventory (
    inv_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    inv_make CHARACTER VARYING(50) NOT NULL,
    inv_model CHARACTER VARYING(50) NOT NULL,
    inv_year CHARACTER(4) NOT NULL CHECK (inv_year ~ '^[0-9]{4}$'),
    inv_description TEXT NOT NULL,
    inv_image CHARACTER VARYING NOT NULL,
    inv_thumbnail CHARACTER VARYING NOT NULL,
    inv_price NUMERIC(10, 2) NOT NULL,
    inv_miles INTEGER NOT NULL,
    inv_color CHARACTER VARYING(30) NOT NULL,
    classification_id INTEGER NOT NULL,
    CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)
);

-- Create foreign key relationship with classification table
ALTER TABLE public.inventory
ADD CONSTRAINT fk_classification FOREIGN KEY (classification_id)
REFERENCES public.classification (classification_id)
ON UPDATE CASCADE
ON DELETE CASCADE;

-- Create an index for classification_id
CREATE INDEX idx_classification_id ON public.inventory (classification_id);
